#!/usr/bin/env bash
# This script transfers a file from our client to a server.

if [ $# -lt 4 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

#assigiing paramental to variables

path_to_files=$1
ip=$2
username=$3
path_to_ssh_key-$4

#disabbling

scp -o "stricthostkeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checking of the transfer was successful
if [#? -eq 0]
then
	echo "FILE was transferd successfully"
else
	echo "file transfer failed"
fi
