#!/usr/bin/env bash
# script to install and setup nginx

sudo apt-get update
apt-get -y install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx Configuration

sudo nginx -t

sudo service nginx reload
