#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# configartion
sudo nginx -t

sudo service nginx reload
