#!/isr/bin/env bash
# performing a 301

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name_;\n\trewrite ^\/redirect_me https:\/\/github.com\/Mulle21 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/mginx/sites-enabled/default

sudo service nginx restart
