#!/usr/bin/env bash
# Configuration web-01 HTTP response header

#update package
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

#create 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom http response header

sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
#test syntax error
sudo nginx -t

#restart nginx
sudo service nginx restart
