#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
apt-get update
apt-get install -y nginx

# ceart an index page
echo "Hello world!" | sudo tee /var/www/html/index.html

#performing a rediraction
string_for_replacement="server_name_;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name_;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# creating custom page
echo "Ceci n'est pas une page" | /var/www/html/404.html

sudo sed -i "/server_name_;/a add_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-enabled/default

#test
sudo nginx -t
#restart
sudo service nginx restart
