#!/usr/bin/env bash
# Installs HAProxy version 2.4 with the following configurations:

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get update
apt-get install -y haproxy=2.4.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
    timeout clinet 30000
    bind 0:80
    default_backend server

backend servers
    timeout connect 3000
    timeout server 30000
    balance roundrobin
    server 126060-web-01 34.202.164.102 check
    server 126060-web-02 54.145.80.224 check
" >> /etc/haproxy/haproxy.cfg

sudo service nginx restart
