#!/usr/bin/env bash
#SSH clinet configuration

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    IdentityFile ~/.ssh/id_rsa
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no

