#!/usr/bin/env bash
# SSH client cconfigration

Host *

    psswordAuthentication n
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
